### PR TITLE
remove default_config for Django versions 3.2+

### PR DESCRIPTION
**Pull request by mschoettle**
Addresses deprecation warning:

> django.utils.deprecation.RemovedInDjango41Warning: 'slippers' defines default_app_config = 'slippers.apps.SlippersConfig'. Django now detects this configuration automatically. You can remove default_app_config.

See: https://docs.djangoproject.com/en/4.0/releases/3.2/#automatic-appconfig-discovery

Btw: Awesome package!

### CODE REVIEW

**Comment by mschoettle** [comment]
@mixxorz Please review :)

**Review by mixxorz — APPROVED** [review]
This looks great. Thank you

**Comment by mschoettle** [comment]
Thanks! The pipeline failure should be fixed now. Is there any chance that this can be released soon?

**Comment by zerolab** [comment]
Considering anything belowe Django 3.2 is no longer supported, perhaps it is time to drop this entirely?

**Comment by mschoettle** [comment]
@mixxorz Could this be merged and released with the next version?

@zerolab Agreed. Could be done in a subsequent PR.

**Review by mixxorz — APPROVED** [review]
Sorry for the delay.

**Comment by zerolab** [comment]
#46 for dropping `default_app_config` (and Python 3.7)

**Pull request merged**
