### PR TITLE
Adding support for multiline template tags.

### PR DESCRIPTION
**Pull request by luanfonceca**
**Description**
For Slippers, one thing became really important was the # of parameters used when reusing components, with just a few parameters we were way past [79/88 characters per line](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#:~:text=We%20allow%20up%20to%2088,f%2Dstrings%2C%20or%20str.) defined by its PEP-8.
This PR introduces a monkey-patch into Django' regex used to tokenize the tags internally, this isn't near great as a official solution but serves as an workaround to it.

I don't see a fix for this any time soon as mentioned here: https://github.com/django/django/pull/2556/ and https://github.com/django/deps/pull/3

**How to Reproduce**
Using Slippers codebase
1. Checkout into this branch
2. Run the tests: `python runtests.py`

Using your own codebase
1. Paste the following snippet inside the `settings.py`
```py
import re
from django.template import base
base.tag_re = re.compile(base.tag_re.pattern, re.DOTALL)
```
2. Open any of your template file, indent any tag used, as follow
```
{% static 'media/folder/other/folder/file.jpg' %}
```
to 
```
{%
  static
  'media/folder/other/folder/file.jpg'
%}
```
3. Assuming you did patched the `tag_re`, everything should work as before with no side-effects

**Motivation**
Before this PR, things got a bit wild when using components:
```
{% #button aria-role="button" x-bind:class="!open ? 'hidden': ''" @click="myHandler" %}Hello{% /button %}
```
And now we could do things like:
```
{%
  #button
  aria-role="button"
  x-bind:class="!open ? 'hidden': ''"
  @click="myHandler"
%}
  Hello
{% /button %}
```

### CODE REVIEW

**Comment by mschoettle** [comment]
Thanks! I just started using slippers and immediately ran into this.

One question though: The change in `slippers/templatetags/slippers.py` will not only apply to slippers but also to the Django project this is used in as a whole right?

**Comment by mixxorz** [comment]
Yes. To be honest I'm not so sure I want to do this.

To be clear having multi-line components is great and makes for better readability, but I'm not sure I want Slippers to monkey patch Django.

**Comment by luanfonceca** [comment]
Hey @mixxorz and @mschoettle, I'm totally in agree with you both. while investigating the feasibility of this changes and possible side-effects, I went over a couple dozens of discussions on the Django about this, but to be honest they will no fix this.

Also this workaround is kind of out of scope for Slippers. I have this running in production for a while now, with no problems. So what I think I'll do now is to close this PR, wrap this changes on its own package and try to create a new discussion on Django deps looking for someone to at least vault for this and in the best case found possible issues by this change

**Comment by mschoettle** [comment]
@luanfonceca Sounds great! Please let me know when you published your own package.

**Pull request closed without merging**
